name: environment.3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base=4.1.3
  - r-ggplot2
  - r-lattice
  - r-caret
  - r-dplyr
  - r-ggplot2
  - r-tidyverse
  - r-plotly
  - r-stringr
